name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Run tests
        run: make test

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Homebrew Formula
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch and checkout main branch
          git fetch origin main
          git checkout main

          # Update the formula
          ./scripts/update-formula.sh

          # Commit and push if there are changes
          git add Formula/macos-notify-bridge.rb
          if git diff --cached --quiet; then
            echo "No changes to Formula"
          else
            git commit -m "Update Homebrew Formula to version ${GITHUB_REF#refs/tags/v}"
            git push origin main
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
